 import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;

public class ChocAnonSystem extends javax.swing.JFrame {

    /**
     * Creates new form ChocAnonSystem
     */
    ServerSystem athread;
    static ChocAnonSystem window;
    public ProviderDB providerDB;
    public MemberDB memberDB;
    public TransactionDB transDB;
    public ProviderDirectory providerDIR;
    public ReportGeneratorAuto autoReport;
    public ReportGenerator rGen;
    boolean startsystem;
    private static String menu = "1 - Display Provider\n"
                               + "2 - Display Member\n"
                               + "3 - Display Service\n"
                               + "4 - Display all Transaction\n"
                               + "5 - Generate a Member Report\n"
                               + "6 - Generate a Provider Report\n"
                               + "7 - Generate a Summary Report\n"
                               + "8 - Interactive Mode\n"
                               + "Please choose the operation you want to do by typing in number:\n";
    
    public ChocAnonSystem() {
        initComponents();
        setLocation(300,100);
        startsystem = false;
        memberDB = new MemberDB();
        try{
			memberDB.ReadFromFile("members.txt");
		} catch(IOException e){
			e.printStackTrace();
		}
        try {
			providerDB = new ProviderDB("ProviderDB.txt");
			transDB = new TransactionDB("transactions.txt");
			providerDIR = new ProviderDirectory("Provider Directory.txt");
			rGen = new ReportGenerator();
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ConnectInfo = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ConnectInfo1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        Title.setText("Chocoholics Anonymous Data Center System");

        jPanel1.setPreferredSize(new java.awt.Dimension(350, 500));
        jPanel1.setSize(new java.awt.Dimension(350, 500));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setLineWrap(true);
        ConnectInfo.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel2.setText("Connection to Terminal:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(ConnectInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(169, 169, 169))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(ConnectInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 500));
        jPanel2.setSize(new java.awt.Dimension(300, 500));

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jButton2.setText("Enter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Local Data:");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setLineWrap(true);
        ConnectInfo1.setViewportView(jTextArea2);

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConnectInfo1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1))
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ConnectInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jButton1.setText("Start System");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(Title)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { 
    	startsystem = true;
        athread = new ServerSystem(window);
        athread.start();
        autoReport = new ReportGeneratorAuto(window);
		autoReport.start();
        jTextArea2.append(menu);
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String string = jTextField1.getText();
        if(!startsystem){
        	jTextArea2.append("Please click the Start button first.\n");
        }else if(string.length() == 0){
        	jTextArea2.append("Please input a number.\n");
        }else{
        	int num = Integer.parseInt(string);
        	switch(num){
        	case 1: providerDB.displayAllByName();
        			jTextArea2.append("Data see the backstage.\n");
        			break;
        	case 2: memberDB.printMap();
        			jTextArea2.append("Data see the backstage.\n");
        			break;
        	case 3: providerDIR.displayAllByName();
        			jTextArea2.append("Data see the backstage.\n");
        			break;
        	case 4: transDB.displayTransactions();
        			jTextArea2.append("Data see the backstage.\n");
        			break;
        	case 5: rGen.generateMemberReports(memberDB, providerDB, transDB, providerDIR);
        			jTextArea2.append("Report Generated succeed.\n");
        			break;
        	case 6: rGen.generateProviderReports(memberDB, providerDB, transDB, providerDIR);
					jTextArea2.append("Report Generated succeed.\n");
					break;
        	case 7: rGen.generateSummaryReport(memberDB, providerDB, transDB, providerDIR);
					jTextArea2.append("Report Generated succeed.\n");
					break;
        	case 8: jTextArea2.append("Please turn to the backstage.\n");
        			interactiveMode();
        			break;
        	default: jTextArea2.append("Wrong input.\n");
        	break;
        	}
        	jTextField1.setText("");
        }
    }                                        
    
    private void interactiveMode(){
    	Scanner in = new Scanner(System.in);
    	String choice = "-1";
    	String memberID = null;
    	String Menu = "Interactive Mode\n1.Add Member\n2.Remove Member\n3.Update Member";
    	System.out.println(Menu);
		choice = in.nextLine();
    	
    	switch (choice){
    	case "1":
    		System.out.println("Please enter the members information");
    		Member toAdd = new Member();
    		toAdd.SetName();
    		System.out.println("Member ID: ");
    		memberID = in.nextLine();
    		toAdd.SetID(Integer.parseInt(memberID));
    		toAdd.SetLocation();
    		memberDB.addMember(toAdd);
    		toAdd.DisplayInformation();
    		System.out.println("Member Added!");
    		
    		try {
				memberDB.writeToFile("members.txt");
			} catch (IOException e) {
				e.printStackTrace();
			}
    		break;
    	case "2":
    		System.out.println("Please enter the members id number: ");
    		memberID = in.nextLine();
    		Member toRemove = memberDB.retrieveMember(Integer.parseInt(memberID));
    		if ( memberDB.removeMember(toRemove) ){
				System.out.println("Member Removed!");
				try {
				memberDB.writeToFile("members.txt");
			    } catch (IOException e) {
				e.printStackTrace();
				}
    		}
    		else
    			System.out.println("Member not found. Exiting.");
    		break;
    	case "3":
    		System.out.println("Please enter the id number of the member you wish to update: ");
    		String tempID = in.nextLine();
    		int memberID1 = Integer.parseInt(tempID);
    		String status = "false";
    		if (memberDB.isValid(memberID1)){
    			System.out.println("Please enter the members new information: ");
    			Member newInfo = new Member();
				newInfo.SetName();
				newInfo.SetID(memberID1);
				newInfo.SetLocation();
				System.out.println("Please enter the members suspended status(true or false): ");
				status = in.nextLine();
				newInfo.SetSuspendedStatus(Boolean.parseBoolean(status));
				System.out.println("Old member information: ");
				Member oldMember = memberDB.retrieveMember(memberID1);
				oldMember.DisplayInformation();
				memberDB.updateMember(oldMember, newInfo);
				Member found = memberDB.retrieveMember(memberID1);
				found.DisplayInformation();
				System.out.println("Member Updated!");
				
				try {
					memberDB.writeToFile("members.txt");
				} catch (IOException e) {
					e.printStackTrace();
				}
    		}
    		else
    			System.out.println("Member number is invalid. Exiting.");
    		break;
    	default:
    		System.out.println("Wrong input!");
    		break;
    	}
    	
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChocAnonSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChocAnonSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChocAnonSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChocAnonSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                window = new ChocAnonSystem();
                window.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify                     
    public javax.swing.JScrollPane ConnectInfo;
    public javax.swing.JScrollPane ConnectInfo1;
    public javax.swing.JLabel Title;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextArea jTextArea2;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
